### ISSUE TITLE
Seurat 4.0.5 requires r-deldir >= 1.0_2

### ISSUE THREAD

**Issue by epruesse** [conda-forge/r-seurat-feedstock#20]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

r-deldir >= 1.0_2 missing in dependencies

Might be an indirect dependency - didn't check that. Installing r-deldir>=1 fixed the issue for me. 

<br/>

```
library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘deldir’ 0.2-10 is being loaded, but >= 1.0.2 is required
In addition: Warning message:
package ‘Seurat’ was built under R version 4.1.1 
```

<details>

**Comment by cbrueffer** [comment]
Closing it since we're at Seurat 5 nowadays. If the issue persists with a recent version please open a new PR.
