### ISSUE TITLE
after arch_rebuild, why is there no Arch Migrator here

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/r-seurat-feedstock#33]
### Additional comment:

l've addedr-rjags to the https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/56e9223877f1fd0096441d00e91393602d4a3369/recipe/migrations/arch_rebuild.txt#L713 file of [conda-forge-pinning-feedstock](https://github.com/conda-forge/conda-forge-pinning-feedstock), but why isn't auto build start here for linux-aarch64?

**Comment by mfansler** [comment]
(Assuming the `r-rjags` is a typo from reposting.) This is still waiting on dependencies, specifically `r-seurat -> r-spatstat.explore -> r-spatstat.random`. The [`r-spatstat.random` has not migrated yet](https://github.com/conda-forge/r-spatstat.random-feedstock/pull/12). This information is available through [the Conda Forge Status page](https://conda-forge.org/status/#aarch64andppc64leaddition).

<img width="537" alt="Screen Shot 2023-09-07 at 3 03 26 PM" src="https://github.com/conda-forge/r-seurat-feedstock/assets/1182216/527bf657-4f46-42e9-aa73-7ce40990b3e3">
